{% set name = "matio-cpp" %}
{% set cxx_name = "lib" + name  %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://github.com/ami-iit/matio-cpp/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 8b5bcec13023c5920dcd1dc857a3a27f481120f689ad15db047d725abe742263

build:
  number: 0

outputs:
  - name: {{ cxx_name }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x.x.x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
      host:
        - libmatio
        - eigen
        - visit_struct
        - catch2
      run:
        - {{ pin_compatible('visit_struct', max_pin='x.x.x') }}

    test:
      commands:
        - test -f $PREFIX/include/matioCpp/matioCpp.h  # [unix]
        - test -f $PREFIX/lib/libmatioCpp${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_INC%\\matioCpp\\matioCpp.h exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\matioCpp.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\matioCpp.dll exit 1  # [win]

  - name: {{ name }}
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
    test:
      commands:
        - test -f $PREFIX/include/matioCpp/matioCpp.h  # [unix]
        - test -f $PREFIX/lib/libmatioCpp${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_INC%\\matioCpp\\matioCpp.h exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\matioCpp.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\matioCpp.dll exit 1  # [win]

about:
  home: https://github.com/ami-iit/matio-cpp
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A C++ wrapper of the matio library, with memory ownership handling, to read and write .mat files.

extra:
  recipe-maintainers:
    - traversaro
